version: 1.0.{build}
branches:
  only:
  - develop
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release 64-bit
platform: x64
clone_depth: 1
environment:
  encrypted_deploy_key:
    secure: ++30FOn93CZGPrm6JMlLQe2A5CDBmwsL4nDAlUlbgLGhDhMCfSe8oz5uvLFdsW2M8+plXilRBWvo/bdfITBHvxOtbHN7kNKRNuUY2z2z4lLy+1mYK5YG33DDkrgMokq3n5keLCh4Z9oTEBQkz+S4GQ==
  encrypted_codesign_key:
    secure: NDyE8YO3Btbxfw7IPI5B9CHCT+NxWKCeI1CoQNBp+BZ64wXV7JAJ7abRAvXhcj0zIQwfVoqCs4/BDhOrcHV/PC6cyi+rMtOo98LyHOpaud8CopzCdeYT+C43zpY6bGK2AyCdbTC44x5ustp3dMWHFA==
  encrypted_codesign_pwd:
    secure: IIXk6ss1lD+C6AFr8w4nZsuiEr3JrUJvGiDFCwnQbRiFP/9B59ivjV6PKY9xzmSU
  artifact_32_bit: Projects\VisualStudio2017\Win32\Release 32-bit\App\Helio.exe
  artifact_64_bit: Projects\VisualStudio2017\x64\Release 64-bit\App\Helio.exe
install:
- SET PATH=%PATH%;C:\Program Files (x86)\Windows Kits\10\bin\x64\
- cmd: git submodule update --init --recursive 2> $null
- ps: >-
    Push-Location ($PSScriptRoot + "\projects\helio-workstation\ThirdParty\ASIO\")

    & ".\get_asio_sdk.ps1"

    Pop-Location
- nuget install secure-file -ExcludeVersion
- secure-file\tools\secure-file -decrypt Projects\Deployment\AppVeyor\deploy-rsa.enc -secret %encrypted_deploy_key% -out deploy-rsa
- secure-file\tools\secure-file -decrypt Projects\Deployment\AppVeyor\code-sign.enc -secret %encrypted_codesign_key% -out sign.p12
cache: ThirdParty\ASIO
build:
  project: Projects\VisualStudio2017\Helio.sln
  verbosity: minimal
deploy_script:
- ps: signtool sign /f sign.p12 /p $env:encrypted_codesign_pwd /t http://timestamp.comodoca.com /v "$env:artifact_64_bit"
- ps: signtool sign /f sign.p12 /p $env:encrypted_codesign_pwd /as /fd sha256 /tr http://timestamp.comodoca.com/?td=sha256 /td sha256 /v "$env:artifact_64_bit"
- 7z a helio-dev.zip "%APPVEYOR_BUILD_FOLDER%\%artifact_64_bit%"
- C:\msys64\usr\bin\bash --login -c "scp -o StrictHostKeyChecking=no -i /c/projects/helio-workstation/deploy-rsa -C /c/projects/helio-workstation/helio-dev.zip deploy@helio.fm:/opt/musehackers/files/ci/helio-dev-64-bit.zip"
