language: node_js
node_js:
  - 8
  - 10
  - 11
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" || "$TRAVIS_NODE_VERSION" == "8" || "$TRAVIS_NODE_VERSION" == "9" ]]; then npm remove midi-test --save-dev; fi
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

